### ISSUE TITLE
Null pointer exception on new posts

### ISSUE THREAD

**Issue by sudocurse** [edmproduction/EDMProduction_IRC_Bot#6]
Despite using fixed jReddit library and successfully getting response json: 

`%02:43 ERROR - Exception encountered when executing event ServerPingEvent(response=dickson.freenode.net) on listener com.slize.edmpircbot.listeners.PrintNewPosts@53f78b68
java.lang.NullPointerException: null
    at com.slize.edmpircbot.listeners.PrintNewPosts.printNewSubmissions(PrintNewPosts.java:94) ~[EDMP%20IRC%20Bot/:na]
    at com.slize.edmpircbot.listeners.PrintNewPosts.onServerPing(PrintNewPosts.java:45) ~[EDMP%20IRC%20Bot/:na]
    at org.pircbotx.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:105) ~[pircbotx-2.0.1.jar:na]
    at org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:119) [pircbotx-2.0.1.jar:na]
    at org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:115) [pircbotx-2.0.1.jar:na]
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6.0_65]
    at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0_65]
    at java.lang.Thread.run(Thread.java:695) [na:1.6.0_65]`

**Comment by nicolaei** [comment]
That was due to the test code I added to display all the posts, I didn't bother to add a try/catch since I wasn't planning to commit that.

Should be fixed with commit 966ee7d335e8a6e169449f288b560f608fada394 though.
